/*DROP TABLE ServiceRequests;
CREATE TABLE ServiceRequests (
    RequestID INTEGER PRIMARY KEY,
    CustomerID INTEGER NOT NULL,
    ProfessionalID INTEGER,
    ServiceID INTEGER NOT NULL,
    RequestDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Status TEXT NOT NULL DEFAULT 'Requested',
    Rating INTEGER,
    Review TEXT,
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID),
    FOREIGN KEY (ProfessionalID) REFERENCES Professionals(ProfessionalID),
    FOREIGN KEY (ServiceID) REFERENCES Services(ServiceID)
);
INSERT INTO ServiceRequests (RequestID, CustomerID, ProfessionalID, ServiceID, Status, Rating, Review)
VALUES (1, 1, 3, 5, 'Requested', NULL, NULL),
       (2, 2, 6, 8, 'Accepted', NULL, NULL),
       (3, 3, 2, 12, 'Closed', 5, 'Excellent service, very satisfied!'),
       (4, 4, 1, 15, 'Requested', NULL, NULL),
       (5, 5, 4, 7, 'Closed', 4, 'Good service but could be quicker.'),
       (6, 6, 5, 2, 'Accepted', NULL, NULL),
       (7, 7, 3, 16, 'Requested', NULL, NULL),
       (8, 8, 7, 6, 'Closed', 5, 'Wonderful experience, highly recommend!'),
       (9, 9, 1, 3, 'Requested', NULL, NULL),
       (10, 10, 2, 10, 'Closed', 4, 'Overall fine, but improvements needed in communication.'),
       (11, 11, 6, 9, 'Requested', NULL, NULL),
       (12, 12, 4, 11, 'Accepted', NULL, NULL),
       (13, 13, 5, 1, 'Requested', NULL, NULL),
       (14, 14, 3, 14, 'Closed', 5, 'Fast and efficient, highly satisfied!'),
       (15, 15, 2, 13, 'Requested', NULL, NULL),
       (16, 16, 7, 8, 'Closed', 4, 'Good quality but price could be better.'),
       (17, 17, 1, 6, 'Requested', NULL, NULL),
       (18, 18, 5, 12, 'Closed', 5, 'Great job, very professional!'),
       (19, 19, 4, 3, 'Requested', NULL, NULL),
       (20, 20, 6, 15, 'Accepted', NULL, NULL),
       (21, 1, 7, 9, 'Requested', NULL, NULL),
       (22, 2, 3, 4, 'Closed', 5, 'Fantastic experience, will book again!'),
       (23, 3, 5, 1, 'Requested', NULL, NULL),
       (24, 4, 6, 7, 'Accepted', NULL, NULL),
       (25, 5, 2, 16, 'Closed', 5, 'Perfect, exceeded expectations!'),
       (26, 6, 1, 12, 'Requested', NULL, NULL),
       (27, 7, 4, 13, 'Closed', 4, 'Decent work, but had some delays.'),
       (28, 8, 5, 14, 'Accepted', NULL, NULL),
       (29, 9, 7, 3, 'Requested', NULL, NULL),
       (30, 10, 3, 2, 'Closed', 4, 'Service was good but lacked attention to detail.'),
       (31, 11, 6, 10, 'Requested', NULL, NULL),
       (32, 12, 4, 6, 'Accepted', NULL, NULL),
       (33, 13, 2, 8, 'Closed', 5, 'Great, would hire again in the future!'),
       (34, 14, 5, 5, 'Requested', NULL, NULL),
       (35, 15, 1, 15, 'Closed', 5, 'Superb quality and fast response time!'),
       (36, 16, 7, 4, 'Requested', NULL, NULL),
       (37, 17, 2, 13, 'Accepted', NULL, NULL),
       (38, 18, 4, 14, 'Closed', 5, 'Extremely happy with the work done.'),
       (39, 19, 6, 16, 'Requested', NULL, NULL),
       (40, 20, 3, 9, 'Closed', 4, 'The job was good but took longer than expected.'),
       (41, 1, 2, 7, 'Requested', NULL, NULL),
       (42, 2, 4, 1, 'Closed', 5, 'Perfect job, will hire again!'),
       (43, 3, 5, 8, 'Requested', NULL, NULL),
       (44, 4, 3, 10, 'Accepted', NULL, NULL),
       (45, 5, 6, 5, 'Closed', 4, 'Nice work, but could improve communication.'),
       (46, 6, 7, 3, 'Requested', NULL, NULL),
       (47, 7, 2, 12, 'Closed', 4, 'Work was good, but pricing was high.'),
       (48, 8, 4, 16, 'Accepted', NULL, NULL),
       (49, 9, 1, 11, 'Requested', NULL, NULL),
       (50, 10, 5, 9, 'Closed', 4, 'Service was fine but took too long to complete.'),
       (51, 11, 3, 6, 'Requested', NULL, NULL),
       (52, 12, 2, 14, 'Closed', 5, 'Excellent, couldn’t have asked for better!'),
       (53, 13, 4, 7, 'Requested', NULL, NULL),
       (54, 14, 5, 5, 'Accepted', NULL, NULL),
       (55, 15, 6, 13, 'Closed', 5, 'Fast, professional, and thorough.'),
       (56, 16, 1, 8, 'Requested', NULL, NULL),
       (57, 17, 3, 10, 'Closed', 5, 'Great service, highly recommend.'),
       (58, 18, 4, 2, 'Requested', NULL, NULL),
       (59, 19, 5, 9, 'Accepted', NULL, NULL),
       (60, 20, 6, 6, 'Closed', 4, 'Service was good but had some room for improvement.'),
       (61, 1, 7, 16, 'Requested', NULL, NULL),
       (62, 2, 4, 1, 'Closed', 5, 'Perfect job, will hire again!'),
       (63, 3, 3, 2, 'Requested', NULL, NULL),
       (64, 4, 6, 13, 'Closed', 5, 'Wonderful experience, will hire again.'),
       (65, 5, 2, 14, 'Requested', NULL, NULL),
       (66, 6, 1, 5, 'Closed', 4, 'Good, but pricing could have been better.'),
       (67, 7, 3, 15, 'Requested', NULL, NULL),
       (68, 8, 7, 8, 'Closed', 5, 'Perfect service, couldn’t have asked for more!'),
       (69, 9, 5, 12, 'Requested', NULL, NULL),
       (70, 10, 4, 6, 'Closed', 4, 'Good service but took longer than expected.'),
       (71, 11, 2, 9, 'Requested', NULL, NULL),
       (72, 12, 3, 16, 'Accepted', NULL, NULL),
       (73, 13, 6, 5, 'Closed', 5, 'Great experience, highly recommended!'),
       (74, 14, 7, 8, 'Requested', NULL, NULL),
       (75, 15, 2, 10, 'Closed', 4, 'Service was good but needed more details.'),
       (76, 16, 1, 7, 'Requested', NULL, NULL),
       (77, 17, 4, 15, 'Closed', 5, 'Excellent, everything went smoothly!'),
       (78, 18, 6, 3, 'Requested', NULL, NULL),
       (79, 19, 5, 11, 'Closed', 4, 'Good work but there’s always room for improvement.'),
       (80, 20, 3, 12, 'Requested', NULL, NULL),
       (81, 1, 4, 5, 'Accepted', NULL, NULL),
       (82, 2, 6, 2, 'Closed', 5, 'Amazing work, highly recommend!'),
       (83, 3, 2, 7, 'Requested', NULL, NULL),
       (84, 4, 5, 9, 'Closed', 4, 'Decent but had some minor issues.'),
       (85, 5, 7, 6, 'Requested', NULL, NULL),
       (86, 6, 1, 4, 'Accepted', NULL, NULL),
       (87, 7, 3, 16, 'Closed', 5, 'Great experience, would use again!'),
       (88, 8, 2, 8, 'Requested', NULL, NULL),
       (89, 9, 4, 14, 'Closed', 4, 'Service was okay, could have been faster.'),
       (90, 10, 5, 3, 'Requested', NULL, NULL),
       (91, 11, 7, 10, 'Closed', 4, 'Good job, but could use some improvements.'),
       (92, 12, 6, 15, 'Requested', NULL, NULL),
       (93, 13, 1, 12, 'Closed', 5, 'Excellent service, will definitely return.'),
       (94, 14, 2, 5, 'Requested', NULL, NULL),
       (95, 15, 3, 16, 'Accepted', NULL, NULL),
       (96, 16, 5, 13, 'Closed', 4, 'Service was good but had some small delays.'),
       (97, 17, 4, 2, 'Requested', NULL, NULL),
       (98, 18, 6, 4, 'Closed', 5, 'Perfect service, couldn’t have been better!'),
       (99, 19, 7, 8, 'Requested', NULL, NULL),
       (100, 20, 2, 15, 'Closed', 5, 'Amazing quality, I will definitely book again!');*/
UPDATE ServiceRequests SET RequestID = 101 WHERE RequestID = 102;
